### ISSUE TITLE
[bug] 多次摁下Alt + C 快捷键，窗口不响应，只有任务栏响应

### ISSUE THREAD

**Issue by witt-bit** [EcoPasteHub/EcoPaste#647] opened 2024-10-12 05:55 UTC
### Describe the bug

多次摁Alt + C

![image](https://github.com/user-attachments/assets/ff98538f-7af4-41a4-9b64-67ef0eff9bd8)

### Application and system information

```text
linux
```

**Comment by ayangweb** [comment] 2024-10-12 06:12
https://github.com/tauri-apps/tauri/issues/11323

**Comment by ayangweb** [comment] 2024-10-12 10:32
Duplicate of #578

**Closed by ayangweb** 2024-10-12 10:32 UTC
Labels: type: bug, status: needs review, platform: Linux
