### ISSUE TITLE
[feat] 一次性粘贴多条剪贴板内容

### ISSUE THREAD

**Issue by Misaia** [EcoPasteHub/EcoPaste#503] opened 2024-09-08 16:52 UTC
### Describe the problem

Hi, please suggest adding a feature.
1. Panel content can be used to copy multiple contents into a single one.
2. Preferences can set the storage location.
3. Add serial number.

### Describe the solution you'd like

1. This makes it easy to merge the collected content.
2. I don’t want to permanently store it on the C drive.
3. There is a serial number for easy memory.

**Comment by ayangweb** [comment] 2024-09-09 00:52
1、under planning
2、Duplicate of #163 
3、Duplicate of #126

**Comment by ayangweb** [comment] 2024-09-13 00:50
https://github.com/EcoPasteHub/EcoPaste/releases/tag/v0.1.0-beta.2

下载使用前请先手动备份好重要数据，然后再尝试更换路径！

**Comment by Misaia** [comment] 2024-09-13 16:39
> https://github.com/EcoPasteHub/EcoPaste/releases/tag/v0.1.0-beta.2
> 
> 下载使用前请先手动备份好重要数据，然后再尝试更换路径！

好的，谢谢。

**Comment by ayangweb** [comment] 2024-11-05 14:09
Duplicate of #260 等支持

**Closed by ayangweb** 2024-11-05 14:09 UTC
Labels: type: feature request
