### ISSUE TITLE
[bug] After accidentally copying a large text content, opening the ecopaste search board is stuck

### ISSUE THREAD

**Issue by Saber-CC** [EcoPasteHub/EcoPaste#628] opened 2024-10-09 09:00 UTC
### Describe the bug

In macos, the contents of a txt text of more than 50 mb were accidentally copied, after opening the ecopaste search box stuck, and the tauri://localhost process usage in the task manager kept exceeding 100%, while the ecopaste process usage exceeding 50%

### Expected behavior

It is best to give an option to limit the size of the content saved by ecopaste

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.1.0",
  "tauriVersion": "1.7.2",
  "platform": "Darwin",
  "platformArch": "aarch64",
  "platformVersion": "14.7.0"
}
```

**Comment by ayangweb** [comment] 2024-10-09 09:55
Duplicate of #569

**Closed by ayangweb** 2024-10-09 09:55 UTC
Labels: type: bug, status: needs triage
